### ISSUE TITLE
Add-on not installing in Blender

### ISSUE THREAD

**Issue by Hidman12** [Sandman13sq/DmrVBM-blender-to-gms2#6]
Hi,
As the title says, I cannot install and use the blender to .vb exporter. I downloaded the zip-file, installed it in Blender under preferences. But even tho it does show up in the Blender add-ons folder (computer file explorer), it does not show up in the Blender program under preferences. 
Hopefully someone can help me with this issue.
Thanks.

**Comment by Hidman12** [comment]
@Sandman13sq

**Comment by Hidman12** [comment]
@Sandman13sq I tried on 3.6, 3.3, 3.1 and 2.9.

**Comment by Hidman12** [comment]
@Sandman13sq And? Have you got a clue on what is going wrong?

**Comment by Sandman13sq** [comment]
Does it show up if you type "dmr" into the search bar in the addons tab?
Sorry, it's hard to help without images, let alone on a Github thread. I'd need your exact steps to see where something could go wrong

**Comment by Sandman13sq** [comment]
@Hidman12

**Comment by Hidman12** [comment]
@Sandman13sq I sent you an email with more details.
