### ISSUE TITLE
Missing path?

### ISSUE THREAD

**Issue by cobs88** [Sandman13sq/DmrVBM-blender-to-gms2#7]
![image_2023-12-17_152805159](https://github.com/Sandman13sq/DmrVBM-blender-to-gms2/assets/154092947/689a0885-14ac-4fb6-9362-f15e3d9a592d)
the operator presets are missing their paths?

**Comment by S1ndn** [comment]
Same^

**Comment by Sandman13sq** [comment]
I'll look into this. The upcoming 1.3 update will either resolve this issue or have some sort of alternative.

**Comment by Sandman13sq** [comment]
The "* Missing Paths *" text shows up when no presets have been previously defined for the version of Blender that you're using. If you move from 3.3 to 3.4 for example, you may need to remake your presets. It's not an issue on your parts.
